/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import entities.Category;
import java.awt.Color;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import services.CategoryCRUD;

/**
 *
 * @author Foura
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() throws SQLException {
        initComponents();
        addRowToTable(productCatTbl);
    }

    CategoryCRUD ccrud = new CategoryCRUD();

    public void addRowToTable(JTable jTbl) throws SQLException {
        DefaultTableModel model = (DefaultTableModel) jTbl.getModel();
        List<Category> categories = ccrud.showAllCategories();
        Object rowData[] = new Object[3];
        for (int i = 0; i < categories.size(); i++) {
            rowData[0] = categories.get(i).getId();
            rowData[1] = categories.get(i).getName();
            rowData[2] = categories.get(i).getDesc();
            model.addRow(rowData);
        }
    }

    public void clearTable(JTable jTbl) {
        jTbl.setModel(new DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "ID_Category", "Category Name", "Category Description"
                }));
        if (productCatTbl.getColumnModel().getColumnCount() > 0) {
            productCatTbl.getColumnModel().getColumn(0).setMinWidth(20);
            productCatTbl.getColumnModel().getColumn(0).setPreferredWidth(80);
            productCatTbl.getColumnModel().getColumn(0).setMaxWidth(80);
            productCatTbl.getColumnModel().getColumn(1).setMinWidth(150);
            productCatTbl.getColumnModel().getColumn(1).setPreferredWidth(200);
            productCatTbl.getColumnModel().getColumn(1).setMaxWidth(250);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPnl = new javax.swing.JPanel();
        menuSep = new javax.swing.JSeparator();
        usersPnl = new javax.swing.JPanel();
        usersLbl = new javax.swing.JLabel();
        productsPnl = new javax.swing.JPanel();
        productsLbl = new javax.swing.JLabel();
        ordersPnl = new javax.swing.JPanel();
        ordersLbl = new javax.swing.JLabel();
        tournamentsPnl = new javax.swing.JPanel();
        tournamentsLbl = new javax.swing.JLabel();
        productCatPnl = new javax.swing.JPanel();
        productCatLbl = new javax.swing.JLabel();
        gameCatPnl = new javax.swing.JPanel();
        gameCatLbl = new javax.swing.JLabel();
        logoPnl = new javax.swing.JPanel();
        logoLbl = new javax.swing.JLabel();
        contentPnl = new javax.swing.JPanel();
        usersCntPnl = new javax.swing.JPanel();
        productsCntPnl = new javax.swing.JPanel();
        ordersCntPnl = new javax.swing.JPanel();
        tournamentsCntPnl = new javax.swing.JPanel();
        productCatCntPnl = new javax.swing.JPanel();
        addProdcutCatForm = new javax.swing.JPanel();
        nameLbl = new javax.swing.JLabel();
        descLbl = new javax.swing.JLabel();
        catNameFld = new javax.swing.JTextField();
        catDescFld = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        productCatTbl = new javax.swing.JTable();
        gameCatCntPnl = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuPnl.setBackground(new java.awt.Color(15, 30, 47));

        usersPnl.setBackground(new java.awt.Color(15, 30, 47));
        usersPnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersPnlMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usersPnlMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usersPnlMouseExited(evt);
            }
        });

        usersLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        usersLbl.setForeground(new java.awt.Color(255, 255, 255));
        usersLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/icons8-user-30.png"))); // NOI18N
        usersLbl.setText("  Users");

        javax.swing.GroupLayout usersPnlLayout = new javax.swing.GroupLayout(usersPnl);
        usersPnl.setLayout(usersPnlLayout);
        usersPnlLayout.setHorizontalGroup(
            usersPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usersPnlLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(usersLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        usersPnlLayout.setVerticalGroup(
            usersPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usersPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usersLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        productsPnl.setBackground(new java.awt.Color(15, 30, 47));
        productsPnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productsPnlMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                productsPnlMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                productsPnlMouseExited(evt);
            }
        });

        productsLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        productsLbl.setForeground(new java.awt.Color(101, 104, 107));
        productsLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/icons8-used-product-30.png"))); // NOI18N
        productsLbl.setText("  Products");

        javax.swing.GroupLayout productsPnlLayout = new javax.swing.GroupLayout(productsPnl);
        productsPnl.setLayout(productsPnlLayout);
        productsPnlLayout.setHorizontalGroup(
            productsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productsPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(productsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        productsPnlLayout.setVerticalGroup(
            productsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productsPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productsLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        ordersPnl.setBackground(new java.awt.Color(15, 30, 47));
        ordersPnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ordersPnlMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ordersPnlMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ordersPnlMouseExited(evt);
            }
        });

        ordersLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ordersLbl.setForeground(new java.awt.Color(101, 104, 107));
        ordersLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/icons8-order-history-30.png"))); // NOI18N
        ordersLbl.setText("  Orders");

        javax.swing.GroupLayout ordersPnlLayout = new javax.swing.GroupLayout(ordersPnl);
        ordersPnl.setLayout(ordersPnlLayout);
        ordersPnlLayout.setHorizontalGroup(
            ordersPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ordersPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ordersLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ordersPnlLayout.setVerticalGroup(
            ordersPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ordersPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ordersLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tournamentsPnl.setBackground(new java.awt.Color(15, 30, 47));
        tournamentsPnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tournamentsPnlMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tournamentsPnlMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tournamentsPnlMouseExited(evt);
            }
        });

        tournamentsLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tournamentsLbl.setForeground(new java.awt.Color(101, 104, 107));
        tournamentsLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/icons8-tournament-30.png"))); // NOI18N
        tournamentsLbl.setText("  Tournaments");

        javax.swing.GroupLayout tournamentsPnlLayout = new javax.swing.GroupLayout(tournamentsPnl);
        tournamentsPnl.setLayout(tournamentsPnlLayout);
        tournamentsPnlLayout.setHorizontalGroup(
            tournamentsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tournamentsPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tournamentsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        tournamentsPnlLayout.setVerticalGroup(
            tournamentsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tournamentsPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tournamentsLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        productCatPnl.setBackground(new java.awt.Color(15, 30, 47));
        productCatPnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productCatPnlMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                productCatPnlMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                productCatPnlMouseExited(evt);
            }
        });

        productCatLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        productCatLbl.setForeground(new java.awt.Color(101, 104, 107));
        productCatLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/icons8-product-documents-30.png"))); // NOI18N
        productCatLbl.setText("  Product Categories");

        javax.swing.GroupLayout productCatPnlLayout = new javax.swing.GroupLayout(productCatPnl);
        productCatPnl.setLayout(productCatPnlLayout);
        productCatPnlLayout.setHorizontalGroup(
            productCatPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productCatPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(productCatLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        productCatPnlLayout.setVerticalGroup(
            productCatPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productCatPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productCatLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        gameCatPnl.setBackground(new java.awt.Color(15, 30, 47));
        gameCatPnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gameCatPnlMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gameCatPnlMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gameCatPnlMouseExited(evt);
            }
        });

        gameCatLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        gameCatLbl.setForeground(new java.awt.Color(101, 104, 107));
        gameCatLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/icons8-category-30.png"))); // NOI18N
        gameCatLbl.setText("  Game Categories");

        javax.swing.GroupLayout gameCatPnlLayout = new javax.swing.GroupLayout(gameCatPnl);
        gameCatPnl.setLayout(gameCatPnlLayout);
        gameCatPnlLayout.setHorizontalGroup(
            gameCatPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameCatPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gameCatLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        gameCatPnlLayout.setVerticalGroup(
            gameCatPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameCatPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gameCatLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        logoPnl.setBackground(new java.awt.Color(15, 30, 47));

        logoLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/logoGlow.png"))); // NOI18N

        javax.swing.GroupLayout logoPnlLayout = new javax.swing.GroupLayout(logoPnl);
        logoPnl.setLayout(logoPnlLayout);
        logoPnlLayout.setHorizontalGroup(
            logoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        logoPnlLayout.setVerticalGroup(
            logoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout menuPnlLayout = new javax.swing.GroupLayout(menuPnl);
        menuPnl.setLayout(menuPnlLayout);
        menuPnlLayout.setHorizontalGroup(
            menuPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuSep)
            .addComponent(usersPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(productsPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ordersPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tournamentsPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(productCatPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(gameCatPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logoPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuPnlLayout.setVerticalGroup(
            menuPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPnlLayout.createSequentialGroup()
                .addComponent(logoPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuSep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usersPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productsPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ordersPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tournamentsPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productCatPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gameCatPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        contentPnl.setBackground(new java.awt.Color(196, 196, 196));

        usersCntPnl.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout usersCntPnlLayout = new javax.swing.GroupLayout(usersCntPnl);
        usersCntPnl.setLayout(usersCntPnlLayout);
        usersCntPnlLayout.setHorizontalGroup(
            usersCntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1008, Short.MAX_VALUE)
        );
        usersCntPnlLayout.setVerticalGroup(
            usersCntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        productsCntPnl.setBackground(new java.awt.Color(0, 255, 204));

        javax.swing.GroupLayout productsCntPnlLayout = new javax.swing.GroupLayout(productsCntPnl);
        productsCntPnl.setLayout(productsCntPnlLayout);
        productsCntPnlLayout.setHorizontalGroup(
            productsCntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 986, Short.MAX_VALUE)
        );
        productsCntPnlLayout.setVerticalGroup(
            productsCntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 678, Short.MAX_VALUE)
        );

        ordersCntPnl.setBackground(new java.awt.Color(255, 255, 51));

        javax.swing.GroupLayout ordersCntPnlLayout = new javax.swing.GroupLayout(ordersCntPnl);
        ordersCntPnl.setLayout(ordersCntPnlLayout);
        ordersCntPnlLayout.setHorizontalGroup(
            ordersCntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 986, Short.MAX_VALUE)
        );
        ordersCntPnlLayout.setVerticalGroup(
            ordersCntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 678, Short.MAX_VALUE)
        );

        tournamentsCntPnl.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout tournamentsCntPnlLayout = new javax.swing.GroupLayout(tournamentsCntPnl);
        tournamentsCntPnl.setLayout(tournamentsCntPnlLayout);
        tournamentsCntPnlLayout.setHorizontalGroup(
            tournamentsCntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1028, Short.MAX_VALUE)
        );
        tournamentsCntPnlLayout.setVerticalGroup(
            tournamentsCntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        productCatCntPnl.setBackground(new java.awt.Color(196, 196, 196));

        addProdcutCatForm.setBackground(new java.awt.Color(235, 235, 235));
        addProdcutCatForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameLbl.setText("Product Category Name");
        addProdcutCatForm.add(nameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 66, 182, 30));

        descLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        descLbl.setText("Product Category Description");
        addProdcutCatForm.add(descLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 107, -1, 30));
        addProdcutCatForm.add(catNameFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 66, 222, 30));
        addProdcutCatForm.add(catDescFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 107, 222, 30));

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        addProdcutCatForm.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 139, 42));

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        addProdcutCatForm.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 139, 42));

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        addProdcutCatForm.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 139, 42));

        productCatTbl.setBackground(new java.awt.Color(235, 235, 235));
        productCatTbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        productCatTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Category", "Category Name", "Category Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        productCatTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productCatTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(productCatTbl);
        if (productCatTbl.getColumnModel().getColumnCount() > 0) {
            productCatTbl.getColumnModel().getColumn(0).setMinWidth(20);
            productCatTbl.getColumnModel().getColumn(0).setPreferredWidth(80);
            productCatTbl.getColumnModel().getColumn(0).setMaxWidth(80);
            productCatTbl.getColumnModel().getColumn(1).setMinWidth(150);
            productCatTbl.getColumnModel().getColumn(1).setPreferredWidth(200);
            productCatTbl.getColumnModel().getColumn(1).setMaxWidth(250);
        }

        javax.swing.GroupLayout productCatCntPnlLayout = new javax.swing.GroupLayout(productCatCntPnl);
        productCatCntPnl.setLayout(productCatCntPnlLayout);
        productCatCntPnlLayout.setHorizontalGroup(
            productCatCntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productCatCntPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(productCatCntPnlLayout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(addProdcutCatForm, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(224, Short.MAX_VALUE))
        );
        productCatCntPnlLayout.setVerticalGroup(
            productCatCntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productCatCntPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addProdcutCatForm, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        gameCatCntPnl.setBackground(new java.awt.Color(153, 0, 153));

        javax.swing.GroupLayout gameCatCntPnlLayout = new javax.swing.GroupLayout(gameCatCntPnl);
        gameCatCntPnl.setLayout(gameCatCntPnlLayout);
        gameCatCntPnlLayout.setHorizontalGroup(
            gameCatCntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 986, Short.MAX_VALUE)
        );
        gameCatCntPnlLayout.setVerticalGroup(
            gameCatCntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout contentPnlLayout = new javax.swing.GroupLayout(contentPnl);
        contentPnl.setLayout(contentPnlLayout);
        contentPnlLayout.setHorizontalGroup(
            contentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usersCntPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(contentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(contentPnlLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(productsCntPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(contentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(contentPnlLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ordersCntPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(contentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tournamentsCntPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(contentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(contentPnlLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(productCatCntPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(contentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(contentPnlLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(gameCatCntPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        contentPnlLayout.setVerticalGroup(
            contentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usersCntPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(contentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(contentPnlLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(productsCntPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(contentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(contentPnlLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ordersCntPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(contentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tournamentsCntPnl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(contentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(contentPnlLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(productCatCntPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(contentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(contentPnlLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(gameCatCntPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contentPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Color unselected = new Color(101, 104, 107);
    private String menuItem = "users";

    private void setMenuItem() {
        switch (menuItem) {
            case "users":
                usersLbl.setForeground(Color.white);
                productsLbl.setForeground(unselected);
                ordersLbl.setForeground(unselected);
                tournamentsLbl.setForeground(unselected);
                productCatLbl.setForeground(unselected);
                gameCatLbl.setForeground(unselected);
                break;
            case "products":
                productsLbl.setForeground(Color.white);
                usersLbl.setForeground(unselected);
                ordersLbl.setForeground(unselected);
                tournamentsLbl.setForeground(unselected);
                productCatLbl.setForeground(unselected);
                gameCatLbl.setForeground(unselected);
                break;
            case "orders":
                ordersLbl.setForeground(Color.white);
                usersLbl.setForeground(unselected);
                productsLbl.setForeground(unselected);
                tournamentsLbl.setForeground(unselected);
                productCatLbl.setForeground(unselected);
                gameCatLbl.setForeground(unselected);
                break;
            case "tournaments":
                tournamentsLbl.setForeground(Color.white);
                usersLbl.setForeground(unselected);
                productsLbl.setForeground(unselected);
                ordersLbl.setForeground(unselected);
                productCatLbl.setForeground(unselected);
                gameCatLbl.setForeground(unselected);
                break;
            case "productCat":
                productCatLbl.setForeground(Color.white);
                usersLbl.setForeground(unselected);
                productsLbl.setForeground(unselected);
                ordersLbl.setForeground(unselected);
                tournamentsLbl.setForeground(unselected);
                gameCatLbl.setForeground(unselected);
                break;
            case "gameCat":
                gameCatLbl.setForeground(Color.white);
                usersLbl.setForeground(unselected);
                productsLbl.setForeground(unselected);
                ordersLbl.setForeground(unselected);
                tournamentsLbl.setForeground(unselected);
                productCatLbl.setForeground(unselected);
                break;
            default:
                usersLbl.setForeground(Color.white);
                productsLbl.setForeground(unselected);
                ordersLbl.setForeground(unselected);
                tournamentsLbl.setForeground(unselected);
                productCatLbl.setForeground(unselected);
                gameCatLbl.setForeground(unselected);
                break;
        }
    }

    private void productsPnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productsPnlMouseClicked
        // TODO add your handling code here:
        usersCntPnl.setVisible(false);
        productsCntPnl.setVisible(true);
        ordersCntPnl.setVisible(false);
        tournamentsCntPnl.setVisible(false);
        productCatCntPnl.setVisible(false);
        gameCatCntPnl.setVisible(false);
        menuItem = "products";
        setMenuItem();
    }//GEN-LAST:event_productsPnlMouseClicked

    private void ordersPnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordersPnlMouseClicked
        // TODO add your handling code here:
        usersCntPnl.setVisible(false);
        productsCntPnl.setVisible(false);
        ordersCntPnl.setVisible(true);
        tournamentsCntPnl.setVisible(false);
        productCatCntPnl.setVisible(false);
        gameCatCntPnl.setVisible(false);
        menuItem = "orders";
        setMenuItem();
    }//GEN-LAST:event_ordersPnlMouseClicked

    private void tournamentsPnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tournamentsPnlMouseClicked
        // TODO add your handling code here:
        usersCntPnl.setVisible(false);
        productsCntPnl.setVisible(false);
        ordersCntPnl.setVisible(false);
        tournamentsCntPnl.setVisible(true);
        productCatCntPnl.setVisible(false);
        gameCatCntPnl.setVisible(false);
        menuItem = "tournaments";
        setMenuItem();
    }//GEN-LAST:event_tournamentsPnlMouseClicked

    private void productCatPnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productCatPnlMouseClicked
        // TODO add your handling code here:
        usersCntPnl.setVisible(false);
        productsCntPnl.setVisible(false);
        ordersCntPnl.setVisible(false);
        tournamentsCntPnl.setVisible(false);
        productCatCntPnl.setVisible(true);
        gameCatCntPnl.setVisible(false);
        menuItem = "productCat";
        setMenuItem();
    }//GEN-LAST:event_productCatPnlMouseClicked

    private void gameCatPnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gameCatPnlMouseClicked
        // TODO add your handling code here:
        usersCntPnl.setVisible(false);
        productsCntPnl.setVisible(false);
        ordersCntPnl.setVisible(false);
        tournamentsCntPnl.setVisible(false);
        productCatCntPnl.setVisible(false);
        gameCatCntPnl.setVisible(true);
        menuItem = "gameCat";
        setMenuItem();
    }//GEN-LAST:event_gameCatPnlMouseClicked

    private void usersPnlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersPnlMouseEntered
        // TODO add your handling code here:
        usersLbl.setForeground(Color.white);
    }//GEN-LAST:event_usersPnlMouseEntered

    private void usersPnlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersPnlMouseExited
        // TODO add your handling code here:
        setMenuItem();
    }//GEN-LAST:event_usersPnlMouseExited

    private void usersPnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersPnlMouseClicked
        // TODO add your handling code here:
        usersCntPnl.setVisible(true);
        productsCntPnl.setVisible(false);
        ordersCntPnl.setVisible(false);
        tournamentsCntPnl.setVisible(false);
        productCatCntPnl.setVisible(false);
        gameCatCntPnl.setVisible(false);
        menuItem = "users";
        setMenuItem();
    }//GEN-LAST:event_usersPnlMouseClicked

    private void productsPnlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productsPnlMouseEntered
        // TODO add your handling code here:
        productsLbl.setForeground(Color.white);
    }//GEN-LAST:event_productsPnlMouseEntered

    private void productsPnlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productsPnlMouseExited
        // TODO add your handling code here:
        setMenuItem();
    }//GEN-LAST:event_productsPnlMouseExited

    private void ordersPnlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordersPnlMouseEntered
        // TODO add your handling code here:
        ordersLbl.setForeground(Color.white);
    }//GEN-LAST:event_ordersPnlMouseEntered

    private void ordersPnlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordersPnlMouseExited
        // TODO add your handling code here:
        setMenuItem();
    }//GEN-LAST:event_ordersPnlMouseExited

    private void tournamentsPnlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tournamentsPnlMouseEntered
        // TODO add your handling code here:
        tournamentsLbl.setForeground(Color.white);
    }//GEN-LAST:event_tournamentsPnlMouseEntered

    private void tournamentsPnlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tournamentsPnlMouseExited
        // TODO add your handling code here:
        setMenuItem();
    }//GEN-LAST:event_tournamentsPnlMouseExited

    private void productCatPnlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productCatPnlMouseEntered
        // TODO add your handling code here:
        productCatLbl.setForeground(Color.white);
    }//GEN-LAST:event_productCatPnlMouseEntered

    private void productCatPnlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productCatPnlMouseExited
        // TODO add your handling code here:
        setMenuItem();
    }//GEN-LAST:event_productCatPnlMouseExited

    private void gameCatPnlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gameCatPnlMouseEntered
        // TODO add your handling code here:
        gameCatLbl.setForeground(Color.white);
    }//GEN-LAST:event_gameCatPnlMouseEntered

    private void gameCatPnlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gameCatPnlMouseExited
        // TODO add your handling code here:
        setMenuItem();
    }//GEN-LAST:event_gameCatPnlMouseExited

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        String catName = catNameFld.getText();
        String catDesc = catDescFld.getText();

        Category c = new Category(catName, catDesc);
        try {
            ccrud.addCategory(c);
            catNameFld.setText("");
            catDescFld.setText("");
            catNameFld.requestFocus();
            JOptionPane.showMessageDialog(addBtn, "Product Category added");
            clearTable(productCatTbl);
            addRowToTable(productCatTbl);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        int SelectIndex = productCatTbl.getSelectedRow();
        String catName = catNameFld.getText();
        String catDesc = catDescFld.getText();
        int catId = Integer.parseInt(productCatTbl.getValueAt(SelectIndex, 0).toString());

        try {
            ccrud.updateCategory(catName, catDesc, catId);
            System.out.println(catId);
            catNameFld.setText("");
            catDescFld.setText("");
            catNameFld.requestFocus();
            addBtn.setEnabled(true);
            JOptionPane.showMessageDialog(addBtn, "Product Category updated");
            clearTable(productCatTbl);
            addRowToTable(productCatTbl);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int SelectIndex = productCatTbl.getSelectedRow();
        int catId = Integer.parseInt(productCatTbl.getValueAt(SelectIndex, 0).toString());

        try {
            ccrud.deleteCategory(catId);
            catNameFld.setText("");
            catDescFld.setText("");
            catNameFld.requestFocus();
            addBtn.setEnabled(true);
            JOptionPane.showMessageDialog(addBtn, "Product Category deleted");
            clearTable(productCatTbl);
            addRowToTable(productCatTbl);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void productCatTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productCatTblMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tbl = (DefaultTableModel) productCatTbl.getModel();
        int SelectIndex = productCatTbl.getSelectedRow();

        catNameFld.setText(tbl.getValueAt(SelectIndex, 1).toString());
        catDescFld.setText(tbl.getValueAt(SelectIndex, 2).toString());

        addBtn.setEnabled(false);
    }//GEN-LAST:event_productCatTblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Menu().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JPanel addProdcutCatForm;
    private javax.swing.JTextField catDescFld;
    private javax.swing.JTextField catNameFld;
    private javax.swing.JPanel contentPnl;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel descLbl;
    private javax.swing.JPanel gameCatCntPnl;
    private javax.swing.JLabel gameCatLbl;
    private javax.swing.JPanel gameCatPnl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logoLbl;
    private javax.swing.JPanel logoPnl;
    private javax.swing.JPanel menuPnl;
    private javax.swing.JSeparator menuSep;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JPanel ordersCntPnl;
    private javax.swing.JLabel ordersLbl;
    private javax.swing.JPanel ordersPnl;
    private javax.swing.JPanel productCatCntPnl;
    private javax.swing.JLabel productCatLbl;
    private javax.swing.JPanel productCatPnl;
    private javax.swing.JTable productCatTbl;
    private javax.swing.JPanel productsCntPnl;
    private javax.swing.JLabel productsLbl;
    private javax.swing.JPanel productsPnl;
    private javax.swing.JPanel tournamentsCntPnl;
    private javax.swing.JLabel tournamentsLbl;
    private javax.swing.JPanel tournamentsPnl;
    private javax.swing.JButton updateBtn;
    private javax.swing.JPanel usersCntPnl;
    private javax.swing.JLabel usersLbl;
    private javax.swing.JPanel usersPnl;
    // End of variables declaration//GEN-END:variables
}
